### ISSUE TITLE
1.4.0 - hotkey bug is present still (when you back to cockpit)

### ISSUE THREAD

**Issue by yoyo251** [Christian1984/vfrmap-for-vr#28] opened 2021-08-04 09:56 UTC
This issue is present still - when you go from outside view (spot or drone) and back to VC in the same time the window with map will be opened. This issue was reported version before from few users (who use hotkey).

This views have keys in MSFS: END or INS. Pls check it. Of course, I only use this keys to return.
Tested with "hotkey 6" (but with the rest hotkeys was the same).  

![1](https://user-images.githubusercontent.com/87498218/128161621-609f343b-5d0e-4c88-8ba5-77342406c75e.jpg)

**Comment by yoyo251** [comment] 2021-08-04 10:03
MSFS SU5+hotfix.

Btw. if you want I can test the next version (find me on Facebook - write "yoyosims PL"). Thx.

**Comment by Christian1984** [comment] 2021-08-04 20:14
Hi @yoyo251 and thanks for your report. That's a duplicate of #22 - Please see my comment here for further details: https://github.com/Christian1984/vfrmap-for-vr/issues/22#issuecomment-883221156

Closed as DUPLICATE!

**Closed as completed by Christian1984** 2021-08-04 20:14 UTC
