### ISSUE TITLE
Incorrect Positioning

### ISSUE THREAD

**Issue by lexmirnov** [Christian1984/vfrmap-for-vr#13] opened 2021-05-19 15:34 UTC
On Map:
https://imgur.com/7JHoRjH
Actual position: parking spot at LFNW.

FSKneeboard Pro 1.2.0

Actions before:
My plane crashed someplace west of LFNW, I restarted the flight from autosave (didn't choose, just hit restart), but then closed the sim (not the server app!). Fired up the sim again, it had been running for some time before I actually returned to flight (the plane was cold & dark). Then opened the map and... this. The issue was solved after restarting the server app.

This said, I've had several cases of wrong positioning in-flight before that, like the current position just stopped updating for no obvious reason. Unfoturnately I couldn't find any kind of log/dump to further analyze the problem.

**Comment by lexmirnov** [comment] 2021-05-19 17:20
One again the plane stopped updating in vr. After I landed and switched to monitor, fskneeboard-panel restarted itself (appeared though I didn't open it) and the position updated correctly. That without restarting server.

**Comment by Christian1984** [comment] 2021-05-20 18:38
Thanks for the report, @lexmirnov - I assume that in the first scenario you described above the server just lost its connection to MSFS. In fact, when MSFS is shutdown, the server should also be shutdown. Weird, though, that this didn't happen...

Regarding that second issue you described: Maybe you could try to reproduce the problem and have a regular browser with active developer tools opened with localhost:9000. This should allow you to monitor any logs and errors in particular that occur on the client side. Next time the position stops updating, could you send me that browser-console-output and/or a screenshot?

Obviously, anyone who encounter the issue described above is invited to follow these steps to identify the cause of the issue described!

**Comment by Christian1984** [comment] 2021-07-19 13:03
This issue has been open for nearly two months now and I haven't received any additional bug reports and/or steps to reproduce the issue. I will close it for now. If the issue does resurface or additional information is available, then please feel free to re-open it.

**Closed as completed by Christian1984** 2021-07-19 13:03 UTC
Labels: bug, help wanted, question
