### ISSUE TITLE
1.4.0. - no icon on icon map

### ISSUE THREAD

**Issue by yoyo251** [Christian1984/vfrmap-for-vr#29] opened 2021-08-04 10:02 UTC
In this version I dont see icon of FS kneeboard:

![Bez tytułu](https://user-images.githubusercontent.com/87498218/128162628-2c8bd9e4-585a-4e56-89a5-1181d4225768.jpg)

**Comment by yoyo251** [comment] 2021-08-04 10:02
MSFS SU5+hotfix.

**Comment by Christian1984** [comment] 2021-08-04 20:16
Thanks for your report. This is a duplicate of #27 and is already fixed. Will be released with hotfix 1.4.1 - See here: https://github.com/Christian1984/vfrmap-for-vr/issues/27#issue-957874172

Closed as DUPLICATE!

**Closed as completed by Christian1984** 2021-08-04 20:16 UTC
